sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-latex-extra texlive-latex-recommended texlive-lang-spanish
script:
- pdflatex -interaction=nonstopmode -halt-on-error jvasel_cv.tex
- pdflatex -interaction=nonstopmode -halt-on-error jvasel_cv.tex
